import {test}from'node:test';import assert from'node:assert/strict';import{SourceTextModule,SyntheticModule}from'node:vm';import{readFile}from'node:fs/promises';
import{PhotoError}from'../lib/photography/model.mjs';
async function route(status){let writes=0;const dependencies={'next/cache':{revalidateTag(){},revalidatePath(){}},'@/lib/photography/server':{photoDb:{},photoBucket(){},requirePhotoOwner:async()=>{if(status)throw new PhotoError('Denied',status);},requireSameOrigin(request){if(request.headers.get('origin')!=='http://localhost:3001')throw new PhotoError('Invalid origin',403);}},'@/lib/photography/model.mjs':{PhotoError,validId:id=>id},'@/lib/photography/admin-service':{initializeCollections:async()=>{writes++;},deletePhoto:async()=>{writes++;return {id:'photo'};},deleteCollection:async()=>{writes++;return {id:'collection'};},library:async()=>({photos:[]})}};const module=new SourceTextModule(await readFile(new URL('../app/api/photography/admin/[...path]/route.js',import.meta.url),'utf8'));await module.link(name=>{const exports=dependencies[name];assert.ok(exports,name);return new SyntheticModule(Object.keys(exports),function(){for(const[key,value]of Object.entries(exports))this.setExport(key,value);});});await module.evaluate();return{api:module.namespace,writes:()=>writes};}
test('admin APIs deny anonymous and non-owner users before reading or writing',async()=>{for(const status of[401,403]){const r=await route(status);const req=new Request('http://localhost:3001/api/photography/admin/initialize',{method:'POST',headers:{origin:'http://localhost:3001','content-type':'application/json'},body:'{}'});assert.equal((await r.api.POST(req,{params:Promise.resolve({path:['initialize']})})).status,status);assert.equal((await r.api.GET(req,{params:Promise.resolve({path:['library']})})).status,status);assert.equal(r.writes(),0);}});
test('cross-origin writes fail even for the owner',async()=>{const r=await route();const req=new Request('http://localhost:3001/api/photography/admin/initialize',{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:'{}'});assert.equal((await r.api.POST(req,{params:Promise.resolve({path:['initialize']})})).status,403);assert.equal(r.writes(),0);});
test('owner requests require valid JSON and a known route',async()=>{const r=await route();for(const[path,body,status]of[[['initialize'],'{',400],[['initialize'],'null',400],[['unknown'],'{}',404],[['initialize'],'{}',200]]){const req=new Request('http://localhost:3001/api/photography/admin/test',{method:'POST',headers:{origin:'http://localhost:3001','content-type':'application/json'},body});assert.equal((await r.api.POST(req,{params:Promise.resolve({path})})).status,status);}assert.equal(r.writes(),1);});

test('permanent deletion requires the owner and same origin before calling the service',async()=>{for(const [status,origin,expected] of [[401,'http://localhost:3001',401],[403,'http://localhost:3001',403],[undefined,'https://evil.test',403],[undefined,'http://localhost:3001',200]]){const r=await route(status);const req=new Request('http://localhost:3001/api/photography/admin/photos/photo/delete',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({revision:1})});assert.equal((await r.api.POST(req,{params:Promise.resolve({path:['photos','photo','delete']})})).status,expected);assert.equal(r.writes(),expected===200?1:0);}});

test('collection deletion requires owner access and same-origin requests',async()=>{
    for(const [status,origin,expected] of [[401,'http://localhost:3001',401],[403,'http://localhost:3001',403],[undefined,'https://evil.test',403],[undefined,'http://localhost:3001',200]]){
        const r=await route(status);
        const req=new Request('http://localhost:3001/api/photography/admin/collections/collection/delete',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({revision:1})});
        assert.equal((await r.api.POST(req,{params:Promise.resolve({path:['collections','collection','delete']})})).status,expected);
        assert.equal(r.writes(),expected===200?1:0);
    }
});
